config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'menus#index'
  get 'lunches' => 'lunches#index'
  resources :notices, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord

  mount_uploader :image, ImageUploader
  belongs_to :menu, optional: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :images, dependent: :delete_all
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController

  def index
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    # @notices = Notice.order('created_at DESC')
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  def index
    @notices = Notice.order('created_at DESC')
    @notice = Notice.where(important: 1).order('created_at DESC')
  end

  def new
    @notice = Notice.new
  end

  def create
    @notice = Notice.new(notice_params)
    if @notice.save
      redirect_to root_path
    else
      @notice = Notice.new
      render :new
    end
  end

  def show
    @notice = Notice.find(params[:id])
  end

  def destroy
    @notice = Notice.find(params[:id])
    if @notice.destroy
      redirect_to root_path
    else
      alert('削除できませんでした。')
    end
  end
  
  private
  def notice_params
    params.require(:notice).permit(:tittle, :content, :important)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EatHp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lunches/index.html.haml
.wrapper
  .left
    = link_to root_path do
      .store-image
    -# = image_tag(".jpg", class: ".store-image")
    = link_to lunches_path do
      .left__lunch
        お昼はランチ
    .left__list
      %ul.left__list__menu
        %li.left__list__menu__list
          メニュー
        %li.left__list__menu__list
          お弁当
        %li.left__list__menu__list
          アクセス
        %li.left__list__menu__list
          お知らせ
      .left__list__booking
        予約をする
      %ul.left__list__sns
        %li.icon
          = icon('fab', 'instagram')
        %li.icon
          = icon('fab', 'facebook-square')
        %li.icon
          = icon('fab', 'twitter-square')
  .lunch
    .lunch__menu
      .lunch__menu__image
      -# = image_tag(".jpg", class: ".store-image")
      .lunch__menu__text
        .lunch_text
          メニュー
        .lunch_content
          あああああああああああ
          %br 良い良い良い良い良い良いい
    %ul.lunch__list
      %li.lunch__list__btn
        ご飯もの
      %li.lunch__list__btn
        麺もの
      %li.lunch__list__btn
        定食
  .menu
    .menu__list
      .menu__list__image
      .menu__list__text
        親子丼
    .menu__list
      .menu__list__image1
      .menu__list__text
        親子丼
    .menu__list
      .menu__list__image
      .menu__list__text
        親子丼
    .menu__list
      .menu__list__image
      .menu__list__text
        親子丼

  .access
    .access__menu
      .access__menu__image
        .image
      -# = image_tag(".jpg", class: ".store-image")
      .access__menu__text
        .access_text
          アクセス
        .access_content
          あああああああああああ
          %br 良い良い良い良い良い良いい


  .left_footer
    .bottom
      %ul.list
        %li.list__name
          = link_to 'スタッフ', "#"
        %li.list__name
          = link_to '店舗のご案内', "#"
        %li.list__name
          = link_to 'お知らせ', "#"
        %li.list__name
          = link_to '求人情報', "#"
      .store

app/views/menus/index.html.haml
.wrapper
  .top
    .top__left
      = link_to '昼はランチ', lunches_path
    .top__center
      .top__center__main
        %ul.list
          %li.list__name
            = link_to 'スタッフ', "#"
          %li.list__name
            = link_to '店舗のご案内', "#"
          %li.list__name
            = link_to 'お知らせ', "#"
          %li.list__name
            = link_to '求人情報', "#"
        -# .store
        = image_tag("/images/DSC_0376_2.jpg", class: "store")
      -# .store-image
      = image_tag("/images/DSC_0428_1.jpg", class: "store-image")
    .top__right
      = link_to '夜はバー', "#"

  .staff-page
    .tittle
      スタッフ
    .staff
      .staff__image
      .staff__detail
        %ul.staff__list
          %li.sub
            店長
          %li.staff-name
            名前
          %li.sub
            プロフィール
        .profile
          ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ

  .store-page
    .tittle
      店舗のご案内
    .store-page__image
    .store-page__detail
      .store-name
        -# = image_tag(".jpg", class: "store-name")
      .store-access
        .address
          〒 000-0000 兵庫県西宮市
        .tel
          お電話: 
          %span.tel-nm 00-0000-0000

  .access-page
    .access-page__detail
      .time
        営業時間
        %ul
          %li.time__list
            ● ランチ (フードL.O.00:00/ドリンクL.O.00:00)
          %li.time__list
            ● バー (フードL.O.00:00/ドリンクL.O.00:00)
          %li.time__list
            ● 定休日: 月曜日と不定休有り
      %ul.seat
        %li.seat-nm
          席数: 00席
        %li.seat-nm
          喫煙: 全席禁煙
          %span.seat-d 喫煙スペース有り
        %li.booking
          = link_to '予約する', "#"
      .access-method
        %ul.access-tittle
          アクセス
          %li.access-m
            ・ 阪神「今津駅」から徒歩0分
            %br・ 阪急「今津駅」から徒歩0分
    .google

  .notice-page
    .tittle
      お知らせ
    %ul.notice-page__list
      %li.notice-page__detail

  .recruit-page
    .tittle
      求人情報
  
  .footer
    .bottom
      %ul.list
        %li.list__name
          = link_to 'スタッフ', "#"
        %li.list__name
          = link_to '店舗のご案内', "#"
        %li.list__name
          = link_to 'お知らせ', "#"
        %li.list__name
          = link_to '求人情報', "#"
      .store
        -# = image_tag(".jpg", class: "store")



-#   .shop__tittle
-#     創作和食 いづみ屋
-#   .shop__tel
-#     0798-34-6176
-#   .shop__image
-#     .shop__image__left
-#       -# = image_tag("eat2.jpg", class: "image")
-#     .shop__image__right
-#       -# = image_tag("eat.png", class: "image")
-#   %ul.shop__menutab
-#     %li.tab
-#       = link_to 'ご案内', "#"
-#     %li.tab
-#       = link_to 'ランチメニュー', "#"
-#     %li.tab
-#       = link_to '露月のおしながき', "#"
-#     %li.tab
-#       = link_to '地図', "#"
-#     %li.tab
-#       = link_to 'お知らせ', notices_path
-#   .shop__detail
-#     営業カレンダー
-#   .shop__detail
-#     店舗情報
-#   .shop__detail__box
-#     .detail__tittle
-#       住所
-#     .detail
-#       兵庫県西宮市津門川町9−6 1F
-#     .detail__tittle
-#       TEL
-#     .detail
-#       0798-34-6176
-#     .detail__tittle
-#       座席
-#     %ul.detail
-#       %li.detail__list
-#         1F : 10席(カウンター4席,テーブル)
-#       %li.detail__list
-#         2F : 4~12席(1組限定)<br> ※全席禁煙(外に灰皿あり)
-#   .shop__detail
-#     お知らせ
-#     .language
-#       - @notices.each do |notices|
-#         .language__detail__box
-#           = link_to (notice_path(notices.id)) do
-#             .language__detail__box__day
-#               = notices.tittle
-#   .shop__detail
-#     採用情報

app/views/notices/index.html.haml
.notise
  - @notices.each do |notices|
    .notice__detail
      = link_to (notice_path(notices.id)) do
        .notice__text
          = notices.tittle
          = notices.content

  - @notice.each do |notice|
    .notice__detail
      = link_to (notice_path(notice.id)) do
        .notice__importants
          - if notice.important == true
            .notice__important
              重要なお知らせ
          - else
        .notice__text
          = notice.tittle
          = notice.content

= link_to 'お知らせ', new_notice_path
= link_to 'トップページ', root_path

app/views/notices/new.html.haml
.notice__page
  = form_with(model: @notice, local: true) do |f|
    %div.tittle
      = f.text_field :tittle, class: 'tittle-field', required: "" , placeholder: 'タイトル(必須 40文字まで)'
    .notice__content
      = f.text_area :content, class: 'text_box', required: "" , placeholder: "マークダウン記法で入力できます"
    .notice__check
      = f.check_box :important, {class: "check_box"}, true, false
    .notice__btn
      = f.submit '投稿する', class: 'form-btn'

app/views/notices/show.html.haml
.notise
  .notice__detail
    .notice__importants
      - if @notice.important == true
        .notice__important
          重要なお知らせ
      - else
    .notice__text
      = @notice.tittle
      = @notice.content
    .notice__delete 
      =link_to "この投稿を削除する", notice_path(@notice.id), method: :delete
    = link_to 'トップページ', root_path